spring:
  application:
    name: service-register-center
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8

logging:
  level:
    root: info
  file:
    max-size: 15MB
    path: service-register-center-log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

server:
  port: 10099
  undertow:
    accesslog:
      enabled: true
      dir: undertow-access-logs
      pattern: common
      rotate: true
      prefix: service_register_center_access_log.
      suffix: log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

eureka:
  instance:
    hostname: node3
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://node1:10097/eureka/,http://node2:10098/eureka/
  server:
    enableSelfPreservation: false #（设为false，关闭自我保护）
    evictionIntervalTimerInMs: 5000 # 清理间隔（单位毫秒，默认是60*1000）